title: Stitches Dye
description: 🧵 Documentation for Stitches Dye, quickly generate elegant Stitches themes with minimum code
twitter_username: TresAbhi_
github_username: TresAbhi

# source: docs
url: 'https://tresabhi.github.io/'

remote_theme: svrooij/just-the-docs@relative-everything

permalink: pretty

logo: 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/310/thread_1f9f5.png'
color_scheme: dark
aux_links:
  'GitHub':
    - 'https://github.com/tresabhi/stitches-dye'
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: 'Edit page on GitHub'
gh_edit_repository: 'https://github.com/tresabhi/stitches-dye'
